// Original practice templates, not standardized or diagnostic models.
export const sceneTemplates = [
  {
    id: "UPDATE",
    name: "进度同步",
    subtitle: "让对方快速知道进展与阻碍",
    steps: ["已完成", "当前阻碍", "下一步"],
    description: "适合简短同步。只保留影响交付的关键变化，下一步说清时间。",
    example: [
      "首页设计已完成，并通过团队评审。",
      "付款页还缺少财务确认的字段，可能影响联调。",
      "今天下午我会约财务确认，明天交付完整页面。",
    ],
  },
  {
    id: "RESULT",
    name: "成果汇报",
    subtitle: "先说成果，再说明价值",
    steps: ["核心成果", "关键证据", "业务价值", "后续计划"],
    description: "适合阶段成果汇报。区分已经验证的结果与预期收益。",
    example: [
      "新版帮助中心已上线。",
      "首周收到的重复咨询从四十次降到二十五次。",
      "这说明常见问题更容易找到答案，但还需继续观察。",
      "下周补齐搜索词对应的内容，再对比两周数据。",
    ],
  },
  {
    id: "HELP",
    name: "向上求助",
    subtitle: "让支持请求具体到可以行动",
    steps: ["当前问题", "影响", "已尝试", "需要支持"],
    description: "适合需要协调或决策时使用。说清需要谁在什么时候做什么。",
    example: [
      "测试环境仍未开通。",
      "若今天无法使用，周五发布可能延期。",
      "我已提交申请并联系维护同事，目前等待审批。",
      "希望您今天下午帮忙确认审批负责人和开通时间。",
    ],
  },
  {
    id: "PROPOSAL",
    name: "方案提议",
    subtitle: "把建议说成可以讨论的行动",
    steps: ["问题", "方案", "收益与代价", "行动请求"],
    description: "适合提出新方案或申请资源。既说收益，也交代成本与不确定性。",
    example: [
      "每次入职培训都要重复准备资料。",
      "建议先整理一份可复用的入职指南。",
      "预计需要两天整理，后续可以减少重复答疑；效果需试用验证。",
      "希望安排一位同事与我本周试做，并邀请下周入职者反馈。",
    ],
  },
  {
    id: "EXPLAIN",
    name: "概念解释",
    subtitle: "从听众熟悉的事讲起",
    steps: ["是什么", "为什么有用", "举例", "怎么用"],
    description: "适合向不了解背景的人解释概念。少用术语，先给具体例子。",
    example: [
      "版本管理就像给文件保留一本修改日记。",
      "它能让我们知道谁改了什么，并找回之前的内容。",
      "比如误删一段说明，可以找到上一次保存的版本恢复。",
      "开始时，每完成一个小修改就保存一次，并写清修改原因。",
    ],
  },
  {
    id: "REVIEW",
    name: "复盘改进",
    subtitle: "从结果差距走到改进行动",
    steps: ["目标", "实际结果", "差距原因", "改进动作"],
    description: "适合活动或项目复盘。用事实描述差距，推测的原因需要验证。",
    example: [
      "我们原计划让三十人参加分享会。",
      "最终二十人到场，十人临时取消。",
      "回访中六人提到时间冲突，这可能是主要原因之一。",
      "下次提前收集可用时段，并在活动前一天再次确认。",
    ],
  },
  {
    id: "REQUEST",
    name: "需求沟通",
    subtitle: "把感受说清，把请求说具体",
    steps: ["具体事实", "感受与影响", "需求", "具体请求"],
    description:
      "适合表达需求和讨论分歧。描述可观察的事实，给对方回应与协商的空间。",
    example: [
      "这周有两次在晚上十一点收到临时修改要求。",
      "我有些疲惫，第二天也难以集中注意力。",
      "我需要相对稳定的休息时间，也希望保证交付质量。",
      "非紧急修改能否在下午六点前集中提出？紧急情况我们再单独商量。",
    ],
  },
];

export const scenarios = [
  {
    id: "update",
    category: "工作汇报",
    title: "简短进度同步",
    framework: "UPDATE",
    reason: "对方需要快速判断是否按计划推进，先说进展和阻碍。",
    alternative: "SUMMARY",
    alternativeReason: "需要同时同步多个项目时，可以按两三个重点展开。",
    prompts: [
      "向主管同步你本周负责的一项工作：完成了什么、卡在哪里、下一步怎么做？",
      "在晨会上同步一次临近截止日期的任务进展。",
    ],
  },
  {
    id: "result",
    category: "工作汇报",
    title: "项目成果汇报",
    framework: "RESULT",
    reason: "先让听众抓住成果，再用证据解释价值，避免流水账。",
    alternative: "STAR",
    alternativeReason: "当重点是讲清你个人如何促成结果时使用。",
    prompts: [
      "向团队汇报一个刚完成的项目，用具体证据说明成果和价值。",
      "汇报一次流程优化的成果，并区分实际效果和预期收益。",
    ],
  },
  {
    id: "help",
    category: "工作汇报",
    title: "向上求助",
    framework: "HELP",
    reason: "明确影响和已做的尝试，方便对方判断应提供什么支持。",
    alternative: "SCQA",
    alternativeReason: "对方不了解背景、需要先解释问题如何出现时使用。",
    prompts: [
      "项目因跨部门依赖受阻，请向主管提出一个明确的协调请求。",
      "资源不足可能影响交付，请说明你已尝试的办法和需要的支持。",
    ],
  },
  {
    id: "proposal",
    category: "提出建议",
    title: "推荐方案与争取资源",
    framework: "PROPOSAL",
    reason: "把问题、代价和行动请求说全，便于讨论是否值得投入。",
    alternative: "COMPARE",
    alternativeReason: "有两种以上候选方案，需要按共同标准选择时使用。",
    prompts: [
      "建议团队试行一种新的协作方式，并说明成本和希望获得的支持。",
      "为改善新人入职体验，提出一个可以小范围试行的方案。",
    ],
  },
  {
    id: "interview",
    category: "面试表达",
    title: "介绍项目经历",
    framework: "STAR",
    reason: "用具体行动与结果呈现能力，让听众分清你的贡献。",
    alternative: "SUMMARY",
    alternativeReason: "只需概括经验优势、不要求讲完整经历时使用。",
    prompts: [
      "向面试官介绍一次你处理突发问题的经历，重点讲自己的行动。",
      "讲一次你与他人合作完成困难任务的经历。",
    ],
  },
  {
    id: "opinion",
    category: "观点讨论",
    title: "发表看法与即兴回答",
    framework: "PREP",
    reason: "简短发言先亮观点，再用一个理由和例子支撑。",
    alternative: "COMPARE",
    alternativeReason: "话题涉及取舍、需要说明不同选择适用条件时使用。",
    prompts: [
      "你认为团队应该减少例会吗？请给出理由和一个例子。",
      "学习新技能时，先系统学习还是先动手尝试？说说你的看法。",
    ],
  },
  {
    id: "explain",
    category: "解释知识",
    title: "讲清概念或工具",
    framework: "EXPLAIN",
    reason: "先建立直观理解，再说明用途和行动步骤。",
    alternative: "SUMMARY",
    alternativeReason: "听众已有基础，只需归纳几个重点时使用。",
    prompts: [
      "向不熟悉的人解释一个你常用的工具，并用生活例子说明它的用途。",
      "向新同事解释什么是任务优先级，以及如何开始使用。",
    ],
  },
  {
    id: "review",
    category: "复盘总结",
    title: "分析结果与改进",
    framework: "REVIEW",
    reason: "先比较目标和实际结果，再分析原因，避免凭印象归因。",
    alternative: "CAUSE",
    alternativeReason: "目标尚不明确、主要任务是解释一个现象时使用。",
    prompts: [
      "复盘一次没有达到预期的活动，提出一项具体改进行动。",
      "复盘一个完成得比预期好的任务，区分可复用的方法与偶然因素。",
    ],
  },
  {
    id: "request",
    category: "日常沟通",
    title: "表达需求与处理分歧",
    framework: "REQUEST",
    reason: "把事实和评价分开，用可协商的请求推动沟通。",
    alternative: "PROBLEM",
    alternativeReason: "双方对问题已有共识，只需讨论具体改进办法时使用。",
    prompts: [
      "同事经常临时打断你的专注时间，请表达影响并提出可协商的请求。",
      "与朋友讨论一次让你不舒服的安排，说清你的需求和希望如何调整。",
    ],
  },
  {
    id: "story",
    category: "故事分享",
    title: "讲经历与个人见闻",
    framework: "TIME",
    reason: "保留起点、转折和结果，让听众跟得上故事的发展。",
    alternative: "STAR",
    alternativeReason: "想突出一次解决问题的行动和能力时使用。",
    prompts: [
      "分享一次计划之外的经历，讲清转折以及你的收获。",
      "讲一个你从害怕到愿意尝试的小故事。",
    ],
  },
];
